stages:
  - build
  - test

build:
  stage: build
  script:
    - 'test -f frontend/index.html'
    - echo "Phase 1 CI"

test:
  stage: test
  image: node:20
  before_script:
    - cd frontend
    # The .npmrc file will handle the legacy-peer-deps automatically
    - npm install
  script:
    - npm run test:ci-simple
    - echo "Test verification complete"

test_selenium:
  stage: test
  image: selenium/standalone-chrome
  before_script:
    - apt-get update && apt-get install -y python3 python3-pip  # Install Python and pip
    - pip3 install selenium  # Install Selenium
  script:
    - cd frontend
    - python3 frontendAcceptanceTests.py  # Run the Selenium tests



test_postman:
    stage: test
    image: 
      name: postman/newman:alpine
      entrypoint: [""]
    before_script:
      - cd backend
    script:
      - newman run wildwareness_api.json



