stages:
  - build
  - test

build:
  stage: build
  script:
    - 'test -f frontend/index.html'
    - echo "Phase 1 CI"

test:
  stage: test
  image: node:20
  before_script:
    - cd frontend
    # The .npmrc file will handle the legacy-peer-deps automatically
    - npm install
  script:
    - npm run test:ci-simple
    - echo "Test verification complete"

selenium:
  stage: selenium-tests
  image: python:latest
  before_script:
    - pip install -r frontend/selenium_tests/requirements.txt
  script:
  - cd frontend/selenium_tests



test_postman:
    stage: test
    image: 
      name: postman/newman:alpine
      entrypoint: [""]
    before_script:
      - cd backend
    script:
      - newman run wildwareness_api.json



