stages:
  - build
  - test

build:
  stage: build
  script:
    - 'test -f frontend/index.html'
    - echo "Phase 1 CI"

# test:
#   stage: test
#   image: node:20
#   before_script:
#     - cd frontend
#     # The .npmrc file will handle the legacy-peer-deps automatically
#     - npm install
#   script:
#     - npm run test:ci-simple
#     - echo "Test verification complete"


test_selenium:
  stage: test
  image: python:3.9
  before_script:
    # Install dependencies for Google Chrome
    # - apt-get update
    # - apt-get install -y wget curl unzip
    # - apt-get install -y google-chrome-stable  # Installs the Chrome browser
    # Install Python dependencies
    - pip install --upgrade pip
    - pip install -r frontend/selenium_tests/requirements.txt
  script:
    - cd frontend/selenium_tests
    - python -m unittest selenium_testing.py


# test_backend:
#   stage: test
#   image: python:3.9
#   before_script:
#     - pip install requests
#     - cd backend/tests
#   script:
#     - python test_api.py


# test_postman:
#     stage: test
#     image: 
#       name: postman/newman:alpine
#       entrypoint: [""]
#     script:
#       - cd backend




