stages:
  - build
  - test

build:
  stage: build
  script:
    - 'test -f frontend/index.html'
    - echo "Phase 1 CI"

test:
  stage: test
  image: node:20
  before_script:
    - cd frontend
    # The .npmrc file will handle the legacy-peer-deps automatically
    - npm install
  script:
    - npm run test:ci-simple
    - echo "Test verification complete"

test_selenium:
  stage: test
  image: python:3.9-slim
  before_script:
    - apt-get update && apt-get install -y wget curl unzip gnupg
    - apt-get install -y google-chrome-stable
    - wget https://chromedriver.storage.googleapis.com/112.0.5615.49/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - mv chromedriver /usr/local/bin/
    - chmod +x /usr/local/bin/chromedriver
    - cd frontend/selenium_tests # Change to the directory with requirements.txt
    - pip install --upgrade pip
    - pip install -r requirements.txt # This will install pytest, selenium, and other dependencies
  script:
    - pytest --maxfail=1 --disable-warnings -q # Run the tests with pytest




test_postman:
    stage: test
    image: 
      name: postman/newman:alpine
      entrypoint: [""]
    before_script:
      - cd backend
    script:
      - newman run wildwareness_api.json



