stages:
  - build
  - test

build:
  stage: build
  script:
    - 'test -f frontend/index.html'
    - echo "Phase 1 CI"

test:
  stage: test
  image: node:20
  before_script:
    - cd frontend
    # The .npmrc file will handle the legacy-peer-deps automatically
    - npm install
  script:
    - npm run test:ci-simple
    - python frontendAcceptanceTests.py
    - echo "Test verification complete"

  test_postman:
    stage: test
    image: 
      name: postman/newman:alpine
      entrypoint: [""]
    before_script:
      - cd backend
    script:
      - newman run collection.json



