version: "3.8"

services:
  backend:
    build:
      context: ./backend  # Path to backend code
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "5000:5000"  # Expose Flask API on port 5000
    restart: unless-stopped
    environment:
      FLASK_APP: "api.py"  # Define the Flask entry point
      FLASK_ENV: "development"  # Enable debug mode for Flask
      FLASK_DEBUG: "1"  # Enable auto-reloading for development
    volumes:
      - ./backend:/app  # Mount backend code for live changes
      - ./backend/database.db:/app/database.db  # Persist SQLite DB file
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend  # Path to frontend code
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80"  # Expose frontend via Nginx on port 80
    restart: unless-stopped
    depends_on:
      - backend  # Ensure frontend starts after backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
